// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// parallel_io //
// ----------- //

#define parallel_io_wrap_target 0
#define parallel_io_wrap 21

static const uint16_t parallel_io_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0                    
    0x00cf, //  1: jmp    pin, 15                    
    0x00e4, //  2: jmp    !osre, 4                   
    0x0015, //  3: jmp    21                         
    0x200b, //  4: wait   0 gpio, 11                 
    0xb842, //  5: nop                    side 1     
    0x6088, //  6: out    pindirs, 8                 
    0x6008, //  7: out    pins, 8                    
    0x6008, //  8: out    pins, 8                    
    0xe001, //  9: set    pins, 1                    
    0x208c, // 10: wait   1 gpio, 12                 
    0xe000, // 11: set    pins, 0                    
    0x200c, // 12: wait   0 gpio, 12                 
    0x6088, // 13: out    pindirs, 8                 
    0x0015, // 14: jmp    21                         
    0xb042, // 15: nop                    side 0     
    0x4008, // 16: in     pins, 8                    
    0x8020, // 17: push   block                      
    0xe001, // 18: set    pins, 1                    
    0x200c, // 19: wait   0 gpio, 12                 
    0xe000, // 20: set    pins, 0                    
    0xa042, // 21: nop                               
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program parallel_io_program = {
    .instructions = parallel_io_program_instructions,
    .length = 22,
    .origin = -1,
};

static inline pio_sm_config parallel_io_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + parallel_io_wrap_target, offset + parallel_io_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void parallel_output_program_init(PIO pio, uint sm, uint offset) 
{    
    pio_sm_config c = parallel_io_program_get_default_config(offset);
    // IO mapping
    sm_config_set_out_pins(&c, 0, 8);
    sm_config_set_in_pins(&c, 0);
    sm_config_set_set_pins(&c, 13, 1);
    sm_config_set_sideset_pins(&c, 10);
    sm_config_set_jmp_pin(&c, 12);
    pio_sm_set_pindirs_with_mask(pio, sm, 1u << 10 | 1u << 13, 1u << 10 | 1u << 13);
    pio_sm_set_pindirs_with_mask(pio, sm, ~(1u << 11 | 1u << 12 | 0xFF), 1u << 11 | 1u << 12 | 0xFF);
    pio_sm_set_pins_with_mask(pio, sm, ~(1u << 13 | 1u << 10), 1u << 13 | 1u << 10); 
    for(int i = 0; i < 8; ++i)
        pio_gpio_init(pio, i);
    for(int i = 10; i < 14; ++i)
        pio_gpio_init(pio, i);
    sm_config_set_out_shift(&c, true, true, 24);
    sm_config_set_in_shift(&c, false, true, 16);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void parallel_io_putc(PIO pio, uint sm, int c) {
    pio_sm_put_blocking(pio, sm, (uint32_t)c);
}
static inline int parallel_io_getc(PIO pio, uint sm) {
    return pio_sm_get_blocking(pio, sm);
}
static inline bool parallel_io_has_data(PIO pio, uint sm)
{
    return !pio_sm_is_rx_fifo_empty(pio, sm);
}

#endif

