// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// parallel_io //
// ----------- //

#define parallel_io_wrap_target 0
#define parallel_io_wrap 21

static const uint16_t parallel_io_program_instructions[] = {
            //     .wrap_target
    0xb042, //  0: nop                    side 0     
    0x00ce, //  1: jmp    pin, 14                    
    0x00e4, //  2: jmp    !osre, 4                   
    0x0015, //  3: jmp    21                         
    0x200b, //  4: wait   0 gpio, 11                 
    0xe001, //  5: set    pins, 1                    
    0xa0eb, //  6: mov    osr, !null                 
    0x6088, //  7: out    pindirs, 8                 
    0x6008, //  8: out    pins, 8                    
    0xb842, //  9: nop                    side 1     
    0x208c, // 10: wait   1 gpio, 12                 
    0xb042, // 11: nop                    side 0     
    0x200c, // 12: wait   0 gpio, 12                 
    0x0015, // 13: jmp    21                         
    0xe000, // 14: set    pins, 0                    
    0xa0e3, // 15: mov    osr, null                  
    0x6088, // 16: out    pindirs, 8                 
    0x4008, // 17: in     pins, 8                    
    0x8020, // 18: push   block                      
    0xb842, // 19: nop                    side 1     
    0x200c, // 20: wait   0 gpio, 12                 
    0xb042, // 21: nop                    side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program parallel_io_program = {
    .instructions = parallel_io_program_instructions,
    .length = 22,
    .origin = -1,
};

static inline pio_sm_config parallel_io_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + parallel_io_wrap_target, offset + parallel_io_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void parallel_output_program_init(PIO pio, uint sm, uint offset) 
{
    pio_sm_set_pins_with_mask(pio, sm, 0x00, 1u << 10 | 1u << 13);
    pio_sm_set_pindirs_with_mask(pio, sm, 0xFF, 1u << 10 | 1u << 13);
    pio_sm_set_pindirs_with_mask(pio, sm, 0x00, 1u << 11 | 1u << 12 | 0xFF);
    pio_gpio_init(pio, 10);
    pio_gpio_init(pio, 13);
    for(int i = 0; i < 8; ++i)
        pio_gpio_init(pio, i);
    pio_gpio_init(pio, 11);
    pio_gpio_init(pio, 12);
    pio_sm_config c = parallel_io_program_get_default_config(offset);
    sm_config_set_out_shift(&c, true, true, 8);
    // IO mapping
    sm_config_set_out_pins(&c, 0, 8);
    sm_config_set_in_pins(&c, 0);
    sm_config_set_set_pins(&c, 10, 1);
    sm_config_set_sideset_pins(&c, 13);
    sm_config_set_sideset(&c, 1, true, false);
    sm_config_set_jmp_pin(&c, 12);
    sm_config_set_clkdiv(&c, 10000000);
    // Configure and start SM
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void parallel_io_putc(PIO pio, uint sm, char c) {
    pio_sm_put_blocking(pio, sm, (uint32_t)c);
}
static inline char parallel_io_getc(PIO pio, uint sm) {
    return pio_sm_get_blocking(pio, sm);
}
static inline bool parallel_io_has_data(PIO pio, uint sm)
{
    return !pio_sm_is_rx_fifo_empty(pio, sm);
}

#endif

